kind: Service
apiVersion: v1
metadata:
   name: oscar-django-service
   labels:
     app: django
     component: oscar
     tier: frontend
spec:
   selector:
     app: django
   type: LoadBalancer
   ports:
   - port: 8000
   
