apiVersion: v1
kind: Secret
metadata:
   name: postgres-credentials
   labels:
     app: django
     component: db
     tier: backend
type: Opaque
data:
   user: cG9zdGdyZXM=
   password: TnV0YW5peC80dSE=
